import type { Metadata } from "next";
import "./globals.css";
import { QueryClientProvider } from "@/providers/query-client-provider";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--playfair-display",
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased p-8 text-white bg-gradient-to-b from-[#5865f2] to-[#060a0b] min-h-screen`}
      >
        <Toaster richColors/>
        <QueryClientProvider>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
